### ISSUE TITLE
Email validation

### ISSUE THREAD

**Issue by brunoamuniz** [TotalCross/totalcross-vscode-plugin#3]
Hey guys, 

We need a validation of the email. Authentication process should have to validate the email of a new user.

Don't stop ppl using if they don't validate, just put a flag at the user data, to let us know if the email is valid or not.

**Comment by ItaloYeltsin** [comment]
For security issues this is critical!

**Comment by ItaloYeltsin** [comment]
E-mail is been validating on registration, but it is still missing validation on login

**Comment by ItaloYeltsin** [comment]
No longer required!
